//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bugger.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bugger.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any good idea, please contact:.
        /// </summary>
        public static string AboutEmailMessage {
            get {
                return ResourceManager.GetString("AboutEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a small tool for give a simple overview of bugs assigned to anyone (or team) in the source control system and show all their status, severity.
        ///It will like the bugger tool for Product Studio in MS. Can helped people a lot in efficiently tracking bugs assigned to he or she.
        ///For anyone want to have a gadget as a simple dashboard for bugs, this is what he want..
        /// </summary>
        public static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AboutOK {
            get {
                return ResourceManager.GetString("AboutOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If any one want to see the source code, please go to:.
        /// </summary>
        public static string AboutSourceCodeMessage {
            get {
                return ResourceManager.GetString("AboutSourceCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string BugAssignedTo {
            get {
                return ResourceManager.GetString("BugAssignedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Date.
        /// </summary>
        public static string BugChangedDate {
            get {
                return ResourceManager.GetString("BugChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create By.
        /// </summary>
        public static string BugCreatedBy {
            get {
                return ResourceManager.GetString("BugCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BugDescription {
            get {
                return ResourceManager.GetString("BugDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string BugID {
            get {
                return ResourceManager.GetString("BugID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pri..
        /// </summary>
        public static string BugPriority {
            get {
                return ResourceManager.GetString("BugPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sev..
        /// </summary>
        public static string BugSeverity {
            get {
                return ResourceManager.GetString("BugSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string BugState {
            get {
                return ResourceManager.GetString("BugState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BugTitle {
            get {
                return ResourceManager.GetString("BugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文(_C).
        /// </summary>
        public static string ChineseMenu {
            get {
                return ResourceManager.GetString("ChineseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodePlex.
        /// </summary>
        public static string CodePlex {
            get {
                return ResourceManager.GetString("CodePlex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd_bigegg@hotamil.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _English.
        /// </summary>
        public static string EnglishMenu {
            get {
                return ResourceManager.GetString("EnglishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string LanguageMenu {
            get {
                return ResourceManager.GetString("LanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string RefreshMenu {
            get {
                return ResourceManager.GetString("RefreshMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the _active proxy.
        /// </summary>
        public static string SettingActiveProxy {
            get {
                return ResourceManager.GetString("SettingActiveProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Member.
        /// </summary>
        public static string SettingAddTeamMember {
            get {
                return ResourceManager.GetString("SettingAddTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string SettingBasicTitle {
            get {
                return ResourceManager.GetString("SettingBasicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string SettingCancel {
            get {
                return ResourceManager.GetString("SettingCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is filter _created by.
        /// </summary>
        public static string SettingIsFilterCreatedBy {
            get {
                return ResourceManager.GetString("SettingIsFilterCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Setting.
        /// </summary>
        public static string SettingMenu {
            get {
                return ResourceManager.GetString("SettingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _Member.
        /// </summary>
        public static string SettingNewTeamMember {
            get {
                return ResourceManager.GetString("SettingNewTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Proxy Settings.
        /// </summary>
        public static string SettingProxysTitle {
            get {
                return ResourceManager.GetString("SettingProxysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh min_utes.
        /// </summary>
        public static string SettingRefreshMinutes {
            get {
                return ResourceManager.GetString("SettingRefreshMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string SettingRemoveTeamMember {
            get {
                return ResourceManager.GetString("SettingRemoveTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Submit.
        /// </summary>
        public static string SettingSubmit {
            get {
                return ResourceManager.GetString("SettingSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Settings.
        /// </summary>
        public static string SettingTeamMemberTitle {
            get {
                return ResourceManager.GetString("SettingTeamMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User _name.
        /// </summary>
        public static string SettingUserName {
            get {
                return ResourceManager.GetString("SettingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show Main Window.
        /// </summary>
        public static string ShowMainWindowMenu {
            get {
                return ResourceManager.GetString("ShowMainWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string SystemMenu {
            get {
                return ResourceManager.GetString("SystemMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bugs assign to or create by team member:.
        /// </summary>
        public static string TeamBugs {
            get {
                return ResourceManager.GetString("TeamBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs for team.
        /// </summary>
        public static string TeamBugsTitle {
            get {
                return ResourceManager.GetString("TeamBugsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Application Error
        ///
        ///{0}.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bugs assign to or create by me:.
        /// </summary>
        public static string UserBugs {
            get {
                return ResourceManager.GetString("UserBugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugs for me.
        /// </summary>
        public static string UserBugsTitle {
            get {
                return ResourceManager.GetString("UserBugsTitle", resourceCulture);
            }
        }
    }
}
