//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bugger.Proxy.TFS.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bugger.Proxy.TFS.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter bug by TFS Field.
        /// </summary>
        public static string BugFilter {
            get {
                return ResourceManager.GetString("BugFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug Property.
        /// </summary>
        public static string BugProperty {
            get {
                return ResourceManager.GetString("BugProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        public static string ConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Settings.
        /// </summary>
        public static string ConnectSettingsTitle {
            get {
                return ResourceManager.GetString("ConnectSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the TFS server..
        /// </summary>
        public static string FailedOnConnect {
            get {
                return ResourceManager.GetString("FailedOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the TFS fields..
        /// </summary>
        public static string FailedOnGetFileds {
            get {
                return ResourceManager.GetString("FailedOnGetFileds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generate Uri.
        /// </summary>
        public static string GenerateUri {
            get {
                return ResourceManager.GetString("GenerateUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS.
        /// </summary>
        public static string HTTPS {
            get {
                return ResourceManager.GetString("HTTPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Settings.
        /// </summary>
        public static string MappingSettingsTitle {
            get {
                return ResourceManager.GetString("MappingSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping the TFS fields with Bugger:.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or Uri of _Team Foundation Server:.
        /// </summary>
        public static string NameOrURIofTFS {
            get {
                return ResourceManager.GetString("NameOrURIofTFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically fill the map settings..
        /// </summary>
        public static string OnAutoFillMapSettings {
            get {
                return ResourceManager.GetString("OnAutoFillMapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect to the TFS server..
        /// </summary>
        public static string OnConnectProgress {
            get {
                return ResourceManager.GetString("OnConnectProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to get the TFS fields..
        /// </summary>
        public static string OnGetFiledsProgress {
            get {
                return ResourceManager.GetString("OnGetFiledsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pat_h:.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port _number:.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre_view:.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bug _Red when priority.
        /// </summary>
        public static string PriorityRed {
            get {
                return ResourceManager.GetString("PriorityRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Protocol:.
        /// </summary>
        public static string Protocal {
            get {
                return ResourceManager.GetString("Protocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Proxy.
        /// </summary>
        public static string SettingViewTitle {
            get {
                return ResourceManager.GetString("SettingViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split the value by &quot;;&quot;.
        /// </summary>
        public static string SplitBy {
            get {
                return ResourceManager.GetString("SplitBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success with some non-critical problem..
        /// </summary>
        public static string SuccessWithError {
            get {
                return ResourceManager.GetString("SuccessWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Test Connection.
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Field.
        /// </summary>
        public static string TFSField {
            get {
                return ResourceManager.GetString("TFSField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User _name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
